name: dev push
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: install code
          uses: actions/checkout
        - name: install npm and node
          uses: actions/setup-node
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm test